# $Id$

LIB= fe_xmpp
SRCS=	fe-xmpp-queries.c \
	fe-xmpp-status.c \
	fe-rosters.c \
	fe-stanzas.c \
	fe-xmpp-core.c \
	module-formats.c \
	xmpp-completion.c

LIB_LIBS = `pkg-config --libs glib-2.0`

include ../rules.mk
