#include "formats.h"

enum {
    XMPPTXT_MODULE_NAME,

    XMPPTXT_FILL_1,

	XMPPTXT_ROSTER_GROUP,
	XMPPTXT_ROSTER_NICK,
	XMPPTXT_ROSTER_RESSOURCE,
	XMPPTXT_ROSTER_RESSOURCE_AWAY,
	XMPPTXT_ROSTER_RESSOURCE_AWAY_STATUS,
	XMPPTXT_BEGIN_OF_ROSTER,
	XMPPTXT_END_OF_ROSTER,
    XMPPTXT_NOT_IN_ROSTER,

    XMPPTXT_FILL_2,

    XMPPTXT_SUBSCRIBE,
    XMPPTXT_SUBSCRIBED,
    XMPPTXT_UNSUBSCRIBE,
    XMPPTXT_UNSUBSCRIBED,

    XMPPTXT_FILL_3,

    XMPPTXT_DEFAULT_EVENT,
    XMPPTXT_DEFAULT_ERROR

};

extern FORMAT_REC fecommon_xmpp_formats[];
